### ISSUE TITLE
Date misaligned

### ISSUE THREAD

**Issue by sidneiweber** [jacekkow/docker-rundeck#1]
When starting the container the system time is correct, however in the panel of rundeck it is with GMT time.
System Time is GMT -3 (Brazilian hour)
Container already restarted, linked with host /etc/localtime and nothing changes in the Rundeck panel

**Comment by jacekkow** [comment]
Java uses /etc/timezone file to determine the timezone, not /etc/localtime.

Nevertheless, the preferred way to set up the time zone should be the use of `TZ` environment variable:
```
docker run ... -e TZ=Europe/Warsaw ...
```

If you need to adjust to the host, you can mount /etc/timezone in addition to /etc/localtime:
```
-v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro
```

References:
https://github.com/docker-library/openjdk/issues/80#issuecomment-355136567
https://github.com/docker-library/openjdk/issues/134 - note that the solution from post 2 is no longer correct, check out this snippet for proper configuration: https://github.com/jacekkow/docker-kodi-custom/blob/master/Dockerfile

**Comment by sidneiweber** [comment]
Thank you,
the solution **-e TZ=Europe/Warsaw** worked perfectly.
